kind: Secret
apiVersion: v1
metadata:
  name: che-ai-assistant-github-token
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-as: env
    controller.devfile.io/mount-to-devworkspace-include: che-ai-assistant
stringData:
  CHE_AI_ASSISTANT_GITHUB_TOKEN: '<put your token here>'
