kind: ConfigMap
apiVersion: v1
metadata:
  name: che-ai-assistant-tasks-config
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-as: env
    controller.devfile.io/mount-to-devworkspace-exclude: che-ai-assistant
    controller.devfile.io/mount-to-devworkspace-include: che-ai-*
data:
  OK_PR_REVIEW_AUTO_POST: 'true'
  CLAUDE_CODE_PRINT_BG_WAIT_CEILING_MS: '0'
