kind: Secret
apiVersion: v1
metadata:
  name: che-ai-assistant-tasks-github-token
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-as: env
    controller.devfile.io/mount-to-devworkspace-exclude: che-ai-assistant
    controller.devfile.io/mount-to-devworkspace-include: che-ai-*
stringData:
  GH_TOKEN: '<put your token here>'
